Repository wecode-bootcamp-korea/34-1st-WATCHACHACHA-frontend, pull requests merged in 2022-06, with the labels that each got.

#5 [34기 김은경]ADD: Footer 구현 완료
  public/index.html
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.js
  src/pages/Main/Main.js
Labels: 완료

#2 [34기 김은경] ADD: 메인페이지 구현 완료
  package-lock.json
  package.json
  public/data/fh.json
  public/data/mainMock.json
  public/data/mainMockModify.json
  public/images/poster/TheGreatGatsby.jpg
  public/images/poster/copyrightfree.jpg
  public/images/poster/copyrightfree_ocean.jpg
  public/index.html
  src/Router.js
  src/pages/Details/Detail.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/components/Film/Film.js
  src/pages/Main/components/Film/Film.scss
  src/pages/Main/components/MainBox/MainBox.js
  src/pages/Main/components/MainBox/MainBox.scss
Labels: 완료

#1 [34기 김민석] ADD: 보고싶어요 UI, 코멘트 UI, 스켈레톤 UI 적용
  package-lock.json
  package.json
  public/images/icon/eyeIcon.png
  public/images/icon/forbiddenIcon.png
  public/images/icon/graph.png
  public/images/icon/penIcon.png
  public/images/icon/positiveAddIcon.png
  public/images/poster/TheGreatGatsby.jpg
  public/images/poster/text.txt
  public/images/userProfile/penguin-img.png
  public/images/userProfile/profile-images.png
  public/images/userProfile/text.txt
  src/pages/Details/Detail.js
  src/pages/Details/components/Aside/Aside.js
  src/pages/Details/components/Aside/Aside.scss
  src/pages/Details/components/BasicInfo/BasicInfo.js
  src/pages/Details/components/BasicInfo/BasicInfo.scss
  src/pages/Details/components/Comment/Comment.js
  src/pages/Details/components/Comment/Comment.scss
  src/pages/Details/components/CommentButton/CommentButton.js
  src/pages/Details/components/CommentButton/CommentButton.scss
  src/pages/Details/components/CommentCard/CommentCard.js
  src/pages/Details/components/CommentCard/CommentCard.scss
  src/pages/Details/components/CommentModal/CommentModal.js
  src/pages/Details/components/CommentModal/CommentModal.scss
  src/pages/Details/components/Comments/Comments.js
  src/pages/Details/components/Comments/Comments.scss
  src/pages/Details/components/Description/Description.js
  src/pages/Details/components/Description/Description.scss
  src/pages/Details/components/DescriptionCard/DescriptionCard.js
  src/pages/Details/components/DescriptionCard/DescriptionCard.scss
  src/pages/Details/components/FilmCrew/FilmCrew.js
  src/pages/Details/components/FilmCrew/FilmCrew.scss
  src/pages/Details/components/Information/Information.js
  src/pages/Details/components/Information/Information.scss
  src/pages/Details/components/PositiveButton/PositiveButton.js
  src/pages/Details/components/PositiveButton/PositiveButton.scss
  src/pages/Details/components/ReviewTextBox/ReviewTextBox.js
  src/pages/Details/components/SkeletonUi/SkeletonUi.js
  src/pages/Details/components/SkeletonUi/SkeletonUi.scss
  src/pages/Details/components/StarScore/StarScore.js
  src/pages/Details/components/StarScore/StarScore.scss
  src/pages/Details/components/StarScoreGraph/StarScoreGraph.js
  src/pages/Details/components/StarScoreGraph/StarScoreGraph.scss
  src/pages/Details/components/ThumbnailImage/ThumbnailImage.js
  src/pages/Details/components/ThumbnailImage/ThumbnailImage.scss
  src/styles/variables.scss
Labels: 추가 기능 구현 중

#6 [34기 이현범] Add: 프로필 페이지
  public/data/userData.json
  public/images/userProfile/profile.png
  src/Router.js
  src/pages/Profile/Profile.js
  src/pages/Profile/Profile.scss
  src/pages/Profile/ProfileSetting.js
  src/pages/Profile/ProfileSetting.scss
Labels: 멘토 리뷰 요청

#8 [34기 김은경] Feature/movie cart master와 merge 요청
  src/Router.js
  src/components/Footer/Footer.scss
  src/components/Nav/Modal/Modal.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Details/Detail.js
  src/pages/Details/components/BasicInfo/BasicInfo.js
  src/pages/Details/components/FilmCrew/FilmCrew.js
  src/pages/Details/components/Information/Information.js
  src/pages/Main/components/MainBox/MainBox.js
  src/pages/MovieCart/Cart.js
  src/pages/MovieCart/Cart.scss
  src/pages/MovieCart/components/WishList/WishList.js
  src/pages/MovieCart/components/WishList/WishList.scss
Labels: 완료

#9 [34기 김민석]ADD: 보고싶어요 기능 모디파이 및 레이아웃 깨짐 현상 처리 (머지요청)
  src/components/Nav/Nav.scss
  src/pages/Details/Detail.js
  src/pages/Details/Detail.scss
  src/pages/Details/components/Aside/Aside.scss
  src/pages/Details/components/CommentButton/CommentButton.js
  src/pages/Details/components/CommentButton/CommentButton.scss
  src/pages/Details/components/CommentCard/CommentCard.js
  src/pages/Details/components/CommentModal/CommentModal.js
  src/pages/Details/components/CommentModal/CommentModal.scss
  src/pages/Details/components/Description/Description.scss
  src/pages/Details/components/DescriptionCard/DescriptionCard.js
  src/pages/Details/components/FilmCrew/FilmCrew.scss
  src/pages/Details/components/Information/Information.js
  src/pages/Details/components/Information/Information.scss
  src/pages/Details/components/PositiveButton/PositiveButton.js
  src/pages/Details/components/SkeletonUi/SkeletonUi.scss
  src/pages/Details/components/ThumbnailImage/ThumbnailImage.scss
Labels: 완료

#7 [34기 이현범] Add : 프로필 페이지 레이아웃 구성 및 백엔드 데이터를 받아와 유저의 프로필창 구현 (merge 요청)
  public/data/userData.json
  public/images/userProfile/profileCover.jpg
  src/Router.js
  src/components/Nav/LoginOnNav.js
  src/components/Nav/Modal/Modal.scss
  src/components/Nav/Nav.js
  src/pages/Profile/Profile.js
  src/pages/Profile/Profile.scss
Labels: 멘토 리뷰 요청
